<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use DateTime;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    
    public function run()
    {
        DB::table('posts')->insert([
            [
                'place_name' => "秋名山",
                'latitude' => 36.4769782 ,
                'longitude' => 138.8680554,
                'genre' => "漫画",
                'title_name' => "イニシャルD",
                'area' => "群馬県",
                'information' => "秋名スピードスターズの本拠地となる峠です。実際の名前は榛名山というそうです。",
                'created_at' => new Datetime(),
                'updated_at' => new Datetime(),
                'category_genre_id' => 1,
                'category_title_id' => 1,
                'category_area_id' => 10,
                'user_id' => 1,
            ],
            [
                'place_name' => "飛騨古川駅",
                'latitude' =>  36.2367302,
                'longitude' => 137.1870279,
                'genre' => "映画",
                'title_name' => "君の名は。",
                'area' => "栃木県",
                'information' => "君の名はのスポットです。",
                'created_at' => new Datetime(),
                'updated_at' => new Datetime(),
                'category_genre_id' => 3,
                'category_title_id' => 2,
                'category_area_id' => 9,
                'user_id' => 1,
            ],
            [
                'place_name' => "アンパンマンミュージアム",
                'latitude' => 33.6476691,
                'longitude' => 133.7789776,
                'genre' => "アニメ",
                'title_name' => "それいけアンパンマン",
                'area' => "高知県",
                'information' => "やなせたかしさんのふるさとです。",
                'created_at' => new Datetime(),
                'updated_at' => new Datetime(),
                'category_genre_id' => 2,
                'category_title_id' => 3,
                'category_area_id' => 39,
                'user_id' => 1,
            ],
            [
                'place_name' => "江ノ島電鉄鎌倉高校前駅",
                'latitude' => 35.3067286 ,
                'longitude' => 139.497982,
                'genre' => "漫画",
                'title_name' => "スラムダンク",
                'area' => "神奈川県",
                'information' => "オープニングにも登場していた駅です",
                'created_at' => new Datetime(),
                'updated_at' => new Datetime(),
                'category_genre_id' => 1,
                'category_title_id' => 5,
                'category_area_id' => 14,
                'user_id' => 1,
            ],
            [
                'place_name' => "あしかがフラワーパーク",
                'latitude' =>  36.3141564,
                'longitude' => 139.5155163,
                'genre' => "漫画",
                'title_name' => "鬼滅の刃",
                'area' => "栃木県",
                'information' => "鬼殺隊最終選抜試験が行われたところです",
                'created_at' => new Datetime(),
                'updated_at' => new Datetime(),
                'category_genre_id' => 1,
                'category_title_id' => 5,
                'category_area_id' => 9,
                'user_id' => 1,
            ],
            [
                'place_name' => "日枝神社",
                'latitude' => 36.133183 ,
                'longitude' => 137.2565162,
                'genre' => "アニメ",
                'title_name' => "君の名は",
                'area' => "岐阜県",
                'information' => "宮水神社のモデルです",
                'created_at' => new Datetime(),
                'updated_at' => new Datetime(),
                'category_genre_id' => 2,
                'category_title_id' => 2,
                'category_area_id' => 21,
                'user_id' => 1,
            ],
            [
                'place_name' => "立石公園",
                'latitude' =>  36.0534868,
                'longitude' => 138.1199542,
                'genre' => "アニメ",
                'title_name' => "君の名は",
                'area' => "長野県",
                'information' => "糸守湖のモデルが見えます",
                'created_at' => new Datetime(),
                'updated_at' => new Datetime(),
                'category_genre_id' => 2,
                'category_title_id' => 2,
                'category_area_id' => 20,
                'user_id' => 1,
            ],
            [
                'place_name' => "須賀神社",
                'latitude' =>  35.6850595,
                'longitude' => 139.718464,
                'genre' => "アニメ",
                'title_name' => "君の名は",
                'area' => "東京都",
                'information' => "ラストシーンに登場していたところです",
                'created_at' => new Datetime(),
                'updated_at' => new Datetime(),
                'category_genre_id' => 2,
                'category_title_id' => 2,
                'category_area_id' => 13,
                'user_id' => 1,
            ],
            [
                'place_name' => "赤城山",
                'latitude' =>  36.5389735,
                'longitude' => 139.1561298,
                'genre' => "漫画",
                'title_name' => "イニシャルD",
                'area' => "群馬県",
                'information' => "赤城レッドサンズの本拠地です",
                'created_at' => new Datetime(),
                'updated_at' => new Datetime(),
                'category_genre_id' => 1,
                'category_title_id' => 1,
                'category_area_id' => 10,
                'user_id' => 1,
            ],
            [
                'place_name' => "妙技山",
                'latitude' => 36.2986177 ,
                'longitude' => 138.738577,
                'genre' => "漫画",
                'title_name' => "イニシャルD",
                'area' => "群馬県",
                'information' => "妙義ナイトキッズの本拠地です",
                'created_at' => new Datetime(),
                'updated_at' => new Datetime(),
                'category_genre_id' => 1,
                'category_title_id' => 1,
                'category_area_id' => 10,
                'user_id' => 1,
            ],
            [
                'place_name' => "碓氷峠",
                'latitude' =>  36.3447219,
                'longitude' => 138.6406842,
                'genre' => "漫画",
                'title_name' => "イニシャルD",
                'area' => "群馬県",
                'information' => "佐藤真子の本拠地です。",
                'created_at' => new Datetime(),
                'updated_at' => new Datetime(),
                'category_genre_id' => 1,
                'category_title_id' => 1,
                'category_area_id' => 10,
                'user_id' => 1,
            ]
            
        ]);
    }

}
